package com.razorpay.dataseed;

public enum ExpectedOutcome {
    MATCHED_PASS_1,
    MATCHED_PASS_2,
    MATCHED_PASS_3,
    EXCEPTION_UNMATCHED_GATEWAY_RECORD,
    EXCEPTION_FEE_VARIANCE,
    EXCEPTION_TIMING_DISCREPANCY,
    EXCEPTION_DUPLICATE_AMOUNT_AMBIGUITY
}